# Generated by Django 4.1.3 on 2023-03-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_print', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('password', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='admin_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black', models.IntegerField()),
                ('colored', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='admin_timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_file',
            field=models.FileField(upload_to=''),
        ),
    ]
