# Generated by Django 4.0.6 on 2023-04-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_print', '0003_uploadedfile_converted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedfile',
            old_name='converted',
            new_name='Nconverted',
        ),
    ]
