# Generated by Django 4.0.6 on 2023-04-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_print', '0004_rename_converted_uploadedfile_nconverted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='Nconverted',
        ),
    ]
