# Generated by Django 4.1.3 on 2023-04-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app_print', '0007_print_option'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_password',
        ),
    ]
